openapi: 3.0.3
info:
  title: AIBOS Public API
  version: 0.1.0
  description: Single source of truth for API contracts. CI will generate clients from this file.
servers:
  - url: http://localhost:8000
paths:
  /health:
    get:
      summary: Liveness probe
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
