[project]
name = "@aibos/backend"
version = "0.1.0"
description = "AIBOS Backend Domain Logic and Business Services"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.0",
    "sqlalchemy>=2.0.0",
    "pydantic>=2.8.0",
    "supabase>=2.0.0"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]
exclude = ["tests*", "*.pyc", "__pycache__*"]
