# Example GitHub Actions CI/CD Workflow for FastAPI

# Save as .github/workflows/ci.yml
name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: Codegen (OpenAPI → TS)
        run: pnpm run codegen

      - name: Lint / Typecheck / Build / Test (Turbo)
        run: |
          pnpm run lint
          pnpm run typecheck
          pnpm run build
          pnpm run test

      - name: Architecture checks (TS)
        run: pnpm run arch:ts

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install import-linter
        run: python -m pip install --upgrade pipx && pipx install import-linter
      - name: Architecture checks (Python)
        run: pnpm run arch:py

      - name: Fail if codegen out-of-date
        run: |
          if [[ -n "$(git status --porcelain packages/shared/clients/ts/openapi.ts)" ]]; then
            echo "::error::OpenAPI clients are stale. Run 'pnpm run codegen' and commit."
            git status --porcelain packages/shared/clients/ts/openapi.ts
            exit 1
          fi
